version: '3.7'
services:
  db:
    image: postgres:12-alpine
    volumes:
      - ./dev/tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
  redis:
    image: redis:5.0.5-alpine
    container_name: redis
    expose:
      - 6379
  app:
    build:
      context: ./server
      target: rosterbater-development
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./server:/app
    environment:
      POSTGRES_HOST: db
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "3000:3000"
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.http-app.rule=Host(`rosterbater.test`)"
      - "traefik.http.routers.https-app.rule=Host(`rosterbater.test`)"
      - "traefik.http.routers.https-app.tls=true"
  reverse-proxy:
    image: traefik
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dev/tmp/certs:/etc/certs
      - ./dev/traefik.toml:/etc/traefik/traefik.toml
      - ./dev/traefik.provider.toml:/etc/traefik/traefik.provider.toml
