version: '3'
services:
  db:
    image: postgres:12-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  redis:
    image: redis:5.0.5-alpine
    container_name: redis
    expose:
      - 6379
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    environment:
      RAILS_ENV: development
      POSTGRES_HOST: db
    ports:
      - "3000:3000"
    depends_on:
      - db
