version: '3.7'
services:
  db:
    image: postgres:12-alpine
    volumes:
      - ./dev/tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
  redis:
    image: redis:5.0.5-alpine
    container_name: redis
    expose:
      - 6379
  app:
    build:
      context: .
      target: rosterbater-development
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/server/app
    environment:
      POSTGRES_HOST: db
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "3000:3000"
    depends_on:
      - db
