apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rosterbater-com
spec:
  secretName: {{ .Release.Name }}-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
    - rosterbater
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
  - {{ .Values.dns.domain }}
  - www.{{ .Values.dns.domain }}
  issuerRef:
    name: letsencrypt-{{ .Values.tls.server }}
    kind: ClusterIssuer
