apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-{{ .Values.tls.server }}
spec:
  acme:
    email: rosterbater@kapsh.com
    {{ if eq .Values.tls.server "production" }}
    server: https://acme-v02.api.letsencrypt.org/directory
    {{ else }}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    {{ end }}
    privateKeySecretRef:
      name: letsencrypt-secret-{{ .Values.tls.server }}
    solvers:
    - http01:
        ingress:
          class: nginx
