apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: mrphillc/rosterbater:latest
          command: ['rails']
          args: ['db:migrate']
          env:
          - name: ROSTERBATER_DATABASE_HOST
            valueFrom:
              secretKeyRef:
                name: rails-secrets
                key: database-host
          - name: ROSTERBATER_DATABASE_USERNAME
            valueFrom:
              secretKeyRef:
                name: rails-secrets
                key: database-username
          - name: ROSTERBATER_DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rails-secrets
                key: database-password
