source 'https://rubygems.org'
ruby '3.1.6'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'pg'
gem 'rails', '~>6.1.0'
# Use postgresql as the database for Active Record
# Use SCSS for stylesheets
gem 'sass-rails'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier'
# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer',  platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
gem 'jquery-tablesorter'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
# gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder'

# until I figure out manifest.js
gem "sprockets", "<4"

gem 'bootstrap-sass'
gem 'factory_bot_rails'
gem 'haml-rails'
gem 'httparty'
gem 'newrelic_rpm'
gem 'nokogiri'
gem 'omniauth'
gem 'omniauth-yahoo-oauth2'
gem 'puma'
gem 'pundit'
gem 'rails-backbone'
gem 'raygun4ruby'
gem 'spreadsheet', '0.9.8'

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
end

group :development, :test do
  gem 'dotenv-rails'
  gem 'faker'
  gem 'pry-rails'
  gem 'rspec-rails', '4.0.0.beta2'
  gem 'rails-controller-testing'
  gem 'webmock', require: false
end

