development:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DATABASE_NAME'] || "ff_development" %>
  pool: 5
  username: <%= ENV['DATABASE_USERNAME'] || "ff" %>
  password: <%= ENV['DATABASE_PASSWORD'] || "" %>

test:
  adapter: postgresql
  encoding: unicode
  database: ff_test
  pool: 5
  username: ff
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: ff_production
  pool: 5
  username: ff
  password:
