apiVersion: apps/v1
kind: Deployment
metadata:
  name: rosterbater-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: rails-app
  template:
    metadata:
      labels:
        app: rails-app
    spec:
      containers:
      - name: rails-app
        image: mrphillc/rosterbater:latest
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: env
        env:
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: rails-secrets
              key: secret_key_base
        - name: YAHOO_KEY
          valueFrom:
            secretKeyRef:
              name: rails-secrets
              key: yahoo-key
        - name: YAHOO_SECRET
          valueFrom:
            secretKeyRef:
              name: rails-secrets
              key: yahoo-secret
        - name: ROSTERBATER_DATABASE_HOST
          valueFrom:
            secretKeyRef:
              name: rails-secrets
              key: database-host
        - name: ROSTERBATER_DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: rails-secrets
              key: database-username
        - name: ROSTERBATER_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rails-secrets
              key: database-password